[tool.poetry]
name = "django-quick-jobs"
version = "0.1.0"
description = "A method of quickly and simply running background jobs in a Django project"
authors = ["Adam Peacock <adam@thepeacock.net>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
Django = ">=3.2"

[tool.poetry.dev-dependencies]
black = "^21.11b1"
pylint = "^2.12.1"
rope = "0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
