name: Release to PyPi
on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.8
      - name: Build and publish
        run: |
          tag="$(git describe --tags --abbrev=0)"
          if ! [[ "$tag" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Unable to read version from ${tag}"
            exit 1
          fi
          version="${tag:1}"
          poetry version $version
          poetry build
          poetry publish --username "__token__" --password "${{secrets.PYPI_TOKEN}}"